# 基础镜像
FROM nginx
# author
MAINTAINER ga

# 挂载目录
VOLUME /home/ga/projects/ga-ui
# 创建目录
RUN mkdir -p /home/ga/projects/ga-ui
# 指定路径
WORKDIR /home/ga/projects/ga-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/ga/projects/ga-ui
