# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ga

# 挂载目录
VOLUME /home/ga
# 创建目录
RUN mkdir -p /home/ga
# 指定路径
WORKDIR /home/ga
# 复制jar文件到路径
COPY ./jar/ga-gateway.jar /home/ga/ga-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","ga-gateway.jar"]
